#!/bin/bash

# This script obtains data from
#	a. collectd csv files
#	b. stackato CLI

# the data obtained, is written in <vpv> bus format
# all .bus files are finally zipped up

# TBD:
# 1. error handling

OLDPWD=.
cd ~/stackato_stats
export PATH=$PATH:/home/stackato/bin:.

# check if somebody is logged into stackato
# if not, bail out

whome=$(perl test_stackato.pl)
if [ $whome = "N/A" ]; then
	echo "Unable to proceed. Login to stackato required."
	cd $OLDPWD
	exit 1
fi

# create collectd bus files
# default interval = 1 minute
# default csv folders = /var/lib/collectd
# change above settings with
# 	-i <interval>m	<<don't forget m at the end>>
#	-c </path/to/csv/files> options

perl collectd_stats.pl -i 1m -c /var/lib/collectd/csv

# login as ramd@hp.com

stackato target https://api.stackato-gkg8.local
stackato login --email ramd@hp.com --passwd 1iso*help

# create stackato user stats bus files
# writes 1 unit of data collected, into bus format files

sh stackato_user_stats.sh

# create stackato app stats bus files
# writes 1 unit of data collected, into bus format files

perl stackato_app_stats.pl

# zip up all bus files
datestr=$(date "+%Y%m%d%H%M%S")
if [ -f  METADATA.bus.template ]; then
	cp -f METADATA.bus.template METADATA.bus
fi

busfile=busfiles-$datestr.zip
zip $busfile *.bus
if [ -s $busfile ]; then
	mkdir -p bus
	cp -f *.bus bus/
 	rm -f *.bus
else
	echo "Busfile not create/zero size"
	cd $OLDPWD
	exit 1
fi

busfile='@'$PWD/$busfile

curl "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPDATECOLLSTATUS&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=1&CUSTOMER=DATACOLLECTORUSER"
curl -v -L "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPDATECOLLSTATUS&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=2&CUSTOMER=DATACOLLECTORUSER"
curl -v -L -F file=$busfile "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPLOADDATAFILES&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=2&CUSTOMER=DATACOLLECTORUSER"
curl -v -L "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPDATECOLLSTATUS&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=4&CUSTOMER=DATACOLLECTORUSER"

rm -f busfiles-$datestr.zip

cd $OLDPWD
exit 0
