#!/bin/bash

# This script obtains data from
#	a. collectd csv files
#	b. stackato CLI

# the data obtained, is written in <vpv> bus format
# all .bus files are finally zipped up

# (Perl) DEPENDENCIES:
# TEXT::CSV module [[ http://search.cpan.org/CPAN/authors/id/M/MA/MAKAMAKA/Text-CSV-1.21.tar.gz ]]
# TEXT::CSV_XS module [[ http://search.cpan.org/CPAN/authors/id/H/HM/HMBRAND/Text-CSV_XS-0.93.tgz ]]

# TBD:
# 1. error handling
# 2. such data is sent to vPV over the wire using cURL utility

OLDPWD=.
cd ~/stackato_stats
export PATH=$PATH:.

# check if somebody is logged into stackato
# if not, bail out

whome=$(perl test_stackato.pl)
if [ $whome = "N/A" ]; then
	echo "Unable to proceed. Login to stackato required."
	cd $OLDPWD
	exit 1
fi

# create collectd bus files
# default interval = 1 minute
# default csv folders = /var/lib/collectd
# change above settings with
# 	-i <interval>m	<<don't forget m at the end>>
#	-c </path/to/csv/files> options

perl collectd_stats.pl -i 1m -c /var/lib/collectd/csv

# create stackato user stats bus files
# writes 1 unit of data collected, into bus format files

sh stackato_user_stats.sh

# create stackato app stats bus files
# writes 1 unit of data collected, into bus format files

perl stackato_app_stats.pl

# zip up all bus files
datestr=$(date "+%Y%m%d%H%M%S")
cp -f METADATA.bus.template METADATA.bus

busfile=busfiles-$datestr.zip
zip $busfile *.bus
if [ -s $busfile ]; then
		rm -f *.bus
else
	echo "Busfile not create/zero size"
	cd $OLDPWD
	exit 1
fi

busfile='@'$PWD/$busfile

curl "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPDATECOLLSTATUS&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=1&CUSTOMER=DATACOLLECTORUSER"
curl -v -L "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPDATECOLLSTATUS&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=2&CUSTOMER=DATACOLLECTORUSER"
curl -v -L -F file=$busfile "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPLOADDATAFILES&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=2&CUSTOMER=DATACOLLECTORUSER"
curl -v -L "http://15.185.229.116:8081/PV/?UPDATESERVICE&ACTION=UPDATECOLLSTATUS&DATASOURCE=STACKATO&DSUSERNAME=administrator&DOMAINID=Stackato&COLL_STATUS=4&CUSTOMER=DATACOLLECTORUSER"

cd $OLDPWD
exit 0
